export enum SysCommandVariant {
    autosave = 0,
    setResource = 1,
    checkpoint = 2,
    kwolokStatue = 7,
    warp = 8,
    applier = 11,
    setHealth = 12,
    setEnergy = 13,
    setSpiritLight = 14,
    equip = 15,
    triggerBind = 16,
    ifEqual = 17,
    ifGreater = 18,
    ifLess = 19,
    disableSync = 20,
    enableSync = 21,
    createWarpIcon = 22,
    destroyWarpIcon = 23,
    ifBounds = 24,
    ifSelfEqual = 25,
    ifSelfGreater = 26,
    ifSelfLess = 27,
    unequip = 28,
    saveString = 29,
    appendString = 30,
}
