/* eslint-disable @typescript-eslint/naming-convention */
enum ShardIconVariant {
    "Overcharge" = 1,
    "Triple Jump" = 2,
    "Wingclip" = 3,
    "Bounty" = 4,
    "Swap" = 5,
    "Crescent Shot (Deprecated)" = 6,
    "Pierce" = 7,
    "Magnet" = 8,
    "Splinter" = 9,
    "Blaze (Deprecated)" = 10,
    "Frost (Deprecated)" = 11,
    "Life Leech (Deprecated)" = 12,
    "Reckless" = 13,
    "Quickshot" = 14,
    "Explosive (Deprecated)" = 15,
    "Ricochet" = 16,
    "Climb (Deprecated)" = 17,
    "Resilience" = 18,
    "Light Harvest" = 19,
    "Compass (Deprecated)" = 20,
    "Waterbreathing (Deprecated)" = 21,
    "Vitality" = 22,
    "Life Harvest" = 23,
    "SpiritWellShield (Deprecated)" = 24,
    "Energy Harvest" = 25,
    "Energy Shard" = 26,
    "Life Pact" = 27,
    "Last Stand" = 28,
    "HarvestOfLight (Deprecated)" = 29,
    "Sense/Secret" = 30,
    "Underwater Efficiency (Deprecated)" = 31,
    "Ultra Bash" = 32,
    "Ultra Grapple" = 33,
    "Overflow" = 34,
    "Thorn" = 35,
    "Catalyst" = 36,
    "Supressor" = 37,
    "Turmoil" = 38,
    "Sticky" = 39,
    "Finesse" = 40,
    "Spirit Surge" = 41,
    "Overcharge (Deprecated)" = 42,
    "Lifeforce" = 43,
    "Deflector" = 44,
    "Stinger" = 45,
    "Fracture" = 46,
    "Arcing" = 47,
}

export default ShardIconVariant;
