const abilityVariants: { [index: string]: string | undefined } = {
    "0": "Bash",
    "3": "Wall Jump",
    "5": "Double Jump",
    "8": "Launch",
    "9": "Magnet",
    "14": "Glide",
    "15": "Spirit Flame",
    "23": "Water Breath",
    "51": "Light Burst",
    "57": "Grapple",
    "62": "Flash",
    "74": "Spike",
    "77": "Regenerate",
    "97": "Bow",
    "98": "Hammer",
    "100": "Sword",
    "101": "Burrow",
    "102": "Dash",
    "104": "Water Dash",
    "106": "Shuriken",
    "108": "Seir",
    "109": "Bow Charge",
    "114": "Hammer Charge",
    "115": "Blaze",
    "116": "Sentry",
    "118": "Flap",
    "120": "Ancestral Light",
    "121": "Ancestral Light",
};
export default abilityVariants;
