const iconVariants: { [index: string]: string | undefined } = {
    "shard:1": "Overcharge",
    "shard:2": "Triple Jump",
    "shard:3": "Wingclip",
    "shard:4": "Bounty",
    "shard:5": "Swap",
    "shard:6": "Crescent Shot (Deprecated)",
    "shard:7": "Pierce",
    "shard:8": "Magnet",
    "shard:9": "Splinter",
    "shard:10": "Blaze (Deprecated)",
    "shard:11": "Frost (Deprecated)",
    "shard:12": "Life Leech (Deprecated)",
    "shard:13": "Reckless",
    "shard:14": "Quickshot",
    "shard:15": "Explosive (Deprecated)",
    "shard:16": "Ricochet",
    "shard:17": "Climb (Deprecated)",
    "shard:18": "Resilience",
    "shard:19": "Light Harvest",
    "shard:20": "Compass (Deprecated)",
    "shard:21": "Waterbreathing (Deprecated)",
    "shard:22": "Vitality",
    "shard:23": "Life Harvest",
    "shard:24": "SpiritWellShield (Deprecated)",
    "shard:25": "Energy Harvest",
    "shard:26": "Energy Shard",
    "shard:27": "Life Pact",
    "shard:28": "Last Stand",
    "shard:29": "HarvestOfLight (Deprecated)",
    "shard:30": "Sense/Secret",
    "shard:31": "Underwater Efficiency (Deprecated)",
    "shard:32": "Ultra Bash",
    "shard:33": "Ultra Grapple",
    "shard:34": "Overflow",
    "shard:35": "Thorn",
    "shard:36": "Catalyst",
    "shard:37": "Supressor",
    "shard:38": "Turmoil",
    "shard:39": "Sticky",
    "shard:40": "Finesse",
    "shard:41": "Spirit Surge",
    "shard:42": "Overcharge (Deprecated)",
    "shard:43": "Lifeforce",
    "shard:44": "Deflector",
    "shard:45": "Stinger",
    "shard:46": "Fracture",
    "shard:47": "Arcing",
    "spell:1000": "Hammer",
    "spell:1001": "Bow",
    "spell:1002": "Sword",
    "spell:1003": "Torch",
    "spell:1004": "Swordstaff",
    "spell:1005": "Chainsword",
    "spell:2000": "Shot",
    "spell:2001": "Homing Missiles",
    "spell:2002": "Wave",
    "spell:2003": "Whirl",
    "spell:2004": "Glow",
    "spell:2005": "Lock On",
    "spell:2006": "Shield",
    "spell:2007": "Invisibility",
    "spell:2008": "Life Absorb",
    "spell:2009": "Shards",
    "spell:2010": "Grenade",
    "spell:2011": "Sentry",
    "spell:2012": "Spear",
    "spell:2013": "Regenerate",
    "spell:2014": "Teleport",
    "spell:2015": "Shuriken",
    "spell:2016": "Blaze",
    "spell:2017": "Turret",
    "spell:2018": "Sein",
    "spell:2019": "Launch",
    "spell:3000": "Bash",
    "spell:3001": "Grapple",
    "spell:3002": "Burrow",
    "spell:3003": "Drill",
    "spell:3004": "Double Jump",
    "spell:3005": "Flap",
    "opher:0": "Sentry",
    "opher:1": "Sentry Upgrade",
    "opher:2": "Hammer",
    "opher:3": "Hammer Upgrade",
    "opher:4": "Shuriken",
    "opher:5": "Shuriken Upgrade",
    "opher:6": "Spear",
    "opher:7": "Spear Upgrade",
    "opher:8": "Blaze",
    "opher:9": "Blaze Upgrade",
    "opher:10": "Water Breath",
    "opher:11": "Fast Travel",
    "lupo:0": "Energy Fragments Map",
    "lupo:1": "Health Fragments Map",
    "lupo:2": "Shards Map",
    "grom:0": "Repair the Spirit Well",
    "grom:1": "Dwelling Repairs",
    "grom:2": "Roofs Over Heads",
    "grom:3": "Onwards and Upwards",
    "grom:4": "Clear the Cave Entrance",
    "grom:5": "Thorny Situation",
    "grom:6": "The Gorlek Touch",
    "tuley:0": "Sela Flowers",
    "tuley:1": "Sticky Grass",
    "tuley:2": "Lightcatchers",
    "tuley:3": "Blue Moon",
    "tuley:4": "Spring Plants",
    "tuley:5": "The Last Seed",
};
export default iconVariants;
