const iconVariants: { [index: string]: string | undefined } = {
    "shard:1": "Overcharge",
    "shard:2": "Triple Jump",
    "shard:3": "Wingclip",
    "shard:4": "Bounty",
    "shard:5": "Swap",
    "shard:6": "Crescent Shot (Deprecated)",
    "shard:7": "Pierce",
    "shard:8": "Magnet",
    "shard:9": "Splinter",
    "shard:10": "Blaze (Deprecated)",
    "shard:11": "Frost (Deprecated)",
    "shard:12": "Life Leech (Deprecated)",
    "shard:13": "Reckless",
    "shard:14": "Quickshot",
    "shard:15": "Explosive (Deprecated)",
    "shard:16": "Ricochet",
    "shard:17": "Climb (Deprecated)",
    "shard:18": "Resilience",
    "shard:19": "Light Harvest",
    "shard:20": "Compass (Deprecated)",
    "shard:21": "Waterbreathing (Deprecated)",
    "shard:22": "Vitality",
    "shard:23": "Life Harvest",
    "shard:24": "SpiritWellShield (Deprecated)",
    "shard:25": "Energy Harvest",
    "shard:26": "Energy Shard",
    "shard:27": "Life Pact",
    "shard:28": "Last Stand",
    "shard:29": "HarvestOfLight (Deprecated)",
    "shard:30": "Sense/Secret",
    "shard:31": "Underwater Efficiency (Deprecated)",
    "shard:32": "Ultra Bash",
    "shard:33": "Ultra Grapple",
    "shard:34": "Overflow",
    "shard:35": "Thorn",
    "shard:36": "Catalyst",
    "shard:37": "Supressor",
    "shard:38": "Turmoil",
    "shard:39": "Sticky",
    "shard:40": "Finesse",
    "shard:41": "Spirit Surge",
    "shard:42": "Overcharge (Deprecated)",
    "shard:43": "Lifeforce",
    "shard:44": "Deflector",
    "shard:45": "Stinger",
    "shard:46": "Fracture",
    "shard:47": "Arcing",
    "spell:1000": "Hammer",
    "spell:1001": "Bow",
    "spell:1002": "Sword",
    "spell:1003": "Torch",
    "spell:1004": "Swordstaff",
    "spell:1005": "Chainsword",
    "spell:2000": "Shot",
    "spell:2001": "Homing Missiles",
    "spell:2002": "Wave",
    "spell:2003": "Whirl",
    "spell:2004": "Glow",
    "spell:2005": "Lock On",
    "spell:2006": "Shield",
    "spell:2007": "Invisibility",
    "spell:2008": "Life Absorb",
    "spell:2009": "Shards",
    "spell:2010": "Grenade",
    "spell:2011": "Sentry",
    "spell:2012": "Spear",
    "spell:2013": "Regenerate",
    "spell:2014": "Teleport",
    "spell:2015": "Shuriken",
    "spell:2016": "Blaze",
    "spell:2017": "Turret",
    "spell:2018": "Sein",
    "spell:2019": "Launch",
    "spell:3000": "Bash",
    "spell:3001": "Grapple",
    "spell:3002": "Burrow",
    "spell:3003": "Drill",
    "spell:3004": "Double Jump",
    "spell:3005": "Flap",
    "map:0": "Keystone",
    "map:1": "Mapstone Pedestal",
    "map:2": "Breakable Wall",
    "map:2:inactive": "Breakable Wall (broken)",
    "map:3": "Broken Breakable Wall",
    "map:4": "Stompable Floor",
    "map:5": "Broken Stompable Floor",
    "map:6": "Two Energy Gate",
    "map:7": "Open Energy Gate",
    "map:8": "Four Keystone Door",
    "map:9": "Open Keystone Door",
    "map:10": "Ability Tree",
    "map:11": "Health Cell Sketch",
    "map:12": "Energy Cell Sketch",
    "map:13": "Save Pedestal",
    "map:13:inactive": "Save Pedestal (inactive)",
    "map:14": "Ability Point Sketch",
    "map:15": "Two Keystone Door",
    "map:16": "Invisible",
    "map:17": "Experience",
    "map:18": "Mapstone Pickup",
    "map:19": "Twelve Energy Gate",
    "map:20": "Ten Energy Gate",
    "map:21": "Eight Energy Gate",
    "map:22": "Six Energy Gate",
    "map:23": "Four Energy Gate",
    "map:24": "Spirit Shard",
    "map:25": "Dialogue",
    "map:26": "Quest Item",
    "map:27": "Shard Slot",
    "map:28": "Teleporter",
    "map:29": "Ore",
    "map:30": "Quest Exclamation Mark",
    "map:31": "Quest Question Mark",
    "map:32": "Race Start",
    "map:32:special": "Race Start (completed)",
    "map:33": "Health Fragment",
    "map:34": "Energy Fragment",
    "map:35": "Seed",
    "map:36": "RaceEnd",
    "map:36:special": "RaceEnd (completed)",
    "map:36:inactive": "RaceEnd (inactive)",
    "map:37": "Eyestone",
    "map:40": "Watermill Door",
    "map:41": "Combat Shrine",
    "map:42": "Small Door",
    "map:43": "Completed Combat Shrine",
    "map:43:inactive": "Shrine (inactive)",
    "map:50": "Baur",
    "map:51": "Opher",
    "map:52": "Tuley",
    "map:53": "Lupo",
    "map:54": "Twillen",
    "map:55": "Tokk",
    "map:56": "Treekeeper",
    "map:57": "Grom",
    "map:58": "Kwolok",
    "map:59": "Motay",
    "map:60": "Creep Heart",
    "map:61": "Miner",
    "map:62": "Spiderling",
    "map:63": "Moki",
    "map:64": "Moki Brave",
    "map:65": "Moki Adventurer",
    "map:66": "Moki Artist",
    "map:67": "Moki Darkness",
    "map:68": "Moki Fashionable",
    "map:69": "Moki Fisherman",
    "map:70": "Moki Frozen",
    "map:71": "Moki KwolokAmulet",
    "map:72": "Moki Spyglass",
    "map:73": "Ku",
    "map:74": "Ice Fisher",
    "map:75": "Siira",
    "opher:0": "Sentry",
    "opher:1": "Sentry Upgrade",
    "opher:2": "Hammer",
    "opher:3": "Hammer Upgrade",
    "opher:4": "Shuriken",
    "opher:5": "Shuriken Upgrade",
    "opher:6": "Spear",
    "opher:7": "Spear Upgrade",
    "opher:8": "Blaze",
    "opher:9": "Blaze Upgrade",
    "opher:10": "Water Breath",
    "opher:11": "Fast Travel",
    "lupo:0": "Energy Fragments Map",
    "lupo:1": "Health Fragments Map",
    "lupo:2": "Shards Map",
    "grom:0": "Repair the Spirit Well",
    "grom:1": "Dwelling Repairs",
    "grom:2": "Roofs Over Heads",
    "grom:3": "Onwards and Upwards",
    "grom:4": "Clear the Cave Entrance",
    "grom:5": "Thorny Situation",
    "grom:6": "The Gorlek Touch",
    "tuley:0": "Sela Flowers",
    "tuley:1": "Sticky Grass",
    "tuley:2": "Lightcatchers",
    "tuley:3": "Blue Moon",
    "tuley:4": "Spring Plants",
    "tuley:5": "The Last Seed",
};
export default iconVariants;
