const shardTypes: { [index: string]: string | undefined } = {
    "1": "Overcharge",
    "2": "Triple Jump",
    "3": "Wingclip",
    "4": "Bounty",
    "5": "Swap",
    "8": "Magnet",
    "9": "Splinter",
    "13": "Reckless",
    "14": "Quickshot",
    "18": "Resilience",
    "19": "Light Harvest",
    "22": "Vitality",
    "23": "Life Harvest",
    "25": "Energy Harvest",
    "26": "Energy",
    "27": "Life Pact",
    "28": "Last Stand",
    "30": "Sense/Secret",
    "32": "Ultra Bash",
    "33": "Ultra Grapple",
    "34": "Overflow",
    "35": "Thorn",
    "36": "Catalyst",
    "38": "Turmoil",
    "39": "Sticky",
    "40": "Finesse",
    "41": "Spirit Surge",
    "43": "Lifeforce",
    "44": "Deflector",
    "46": "Fracture",
    "47": "Arcing",
};
export default shardTypes;
