const teleporterVariants: { [index: string]: string | undefined } = {
    "0": "Midnight Burrows Teleporter",
    "1": "Howl’s Den Teleporter",
    "2": "East Luma Teleporter",
    "3": "Wellspring Teleporter",
    "4": "Baur’s Reach Teleporter",
    "5": "Kwolok’s Hollow Teleporter",
    "6": "Mouldwood Depths Teleporter",
    "7": "West Woods Teleporter",
    "8": "East Woods Teleporter",
    "9": "West Wastes Teleporter",
    "10": "East Wastes Teleporter",
    "11": "Outer Ruins Teleporter",
    "12": "Willow’s End Teleporter",
    "13": "West Luma Teleporter",
    "14": "Inner Ruins Teleporter",
    "15": "Shriek Teleporter",
    "16": "Inkwater Marsh Teleporter",
    "17": "Glades Teleporter",
};
export default teleporterVariants;
