export enum ItemVariant {
    spiritLight = 0,
    resource = 1,
    ability = 2,
    shard = 3,
    sysCommand = 4,
    teleporter = 5,
    message = 6,
    setUberState = 8,
    water = 9,
    bonusItem = 10,
    bonusUpgrade = 11,
    relic = 14,
    progressMessage = 15,
    wheelCommand = 16,
    shopCommand = 17,
}
